```{r ProcessingSteps, echo = FALSE}
NC_PROCESSING_STEPS_TABLE = data.table::data.table(DATA_SET = c("NC_COMBINED", "NC_MAPPED_SPECIES", "NC_MAPPED_SPECIES_GEAR", "NC_MAPPED_SPECIES_GEAR_FLEET", "NC"), 
           DESCRIPTION = c("All species, gears, and fleets", "Species mapped to the ASFIS code list", "Gears mapped to the ISSCFG code list", "Fleets mapped to the FIRMS fleet code list", "Filter on GTA species"), 
           SPECIES = c(length(unique(NC_COMBINED$SPECIES_CODE)), length(unique(NC_MAPPED_SPECIES$species)), length(unique(NC_MAPPED_SPECIES_GEAR$species)), length(unique(NC_MAPPED_SPECIES_GEAR_FLEET$species)), length(unique(NC$species))), 
           GEARS = c(length(unique(NC_COMBINED$GEAR_CODE)), length(unique(NC_MAPPED_SPECIES$GEAR_CODE)), length(unique(NC_MAPPED_SPECIES_GEAR$gear_type)), length(unique(NC_MAPPED_SPECIES_GEAR_FLEET$gear_type)), length(unique(NC$gear_type))), 
           FLEETS = c(length(unique(NC_COMBINED$FLEET_CODE)), length(unique(NC_MAPPED_SPECIES$FLEET_CODE)), length(unique(NC_MAPPED_SPECIES_GEAR$FLEET_CODE)), length(unique(NC_MAPPED_SPECIES_GEAR_FLEET$fishing_fleet)), length(unique(NC$fishing_fleet))), 
           CATCH = c(pn(round(sum(NC_COMBINED$CATCH))), pn(round(sum(NC_MAPPED_SPECIES$CATCH))), pn(round(sum(NC_MAPPED_SPECIES_GEAR$CATCH))), pn(round(sum(NC_MAPPED_SPECIES_GEAR_FLEET$CATCH))), pn(round(sum(NC$CATCH))))
           )
```

```{r CAPSBBSummaryProcessingTable}
DT::datatable(NC_PROCESSING_STEPS_TABLE, rownames = FALSE, options = list(dom = 't')) %>% formatStyle('CATCH', `text-align` = 'right')
```
