```{r CA_Export, echo = TRUE}
# Build the monthly aggregated data set for all fisheries
IOTC_CA_M_LEVEL0 = CA[, .(measurement_value = sum(CATCH)), 
                                                             keyby = .(
                                                               fishing_fleet, 
                                                               time_start, 
                                                               time_end, 
                                                               geographic_identifier = FISHING_GROUND_CODE, 
                                                               gear_type, 
                                                               fishing_mode, 
                                                               species, 
                                                               measurement, 
                                                               measurement_type, 
                                                               measurement_obs, 
                                                               measurement_unit = unit, 
                                                               source_authority
                                                               )]

# Order the columns
setcolorder(IOTC_CA_M_LEVEL0, neworder = c("fishing_fleet", "time_start", "time_end", "geographic_identifier", "gear_type", "fishing_mode", "species", "measurement", "measurement_type", "measurement_value", "measurement_unit", "measurement_obs"))

# Export the data set
write.csv(IOTC_CA_M_LEVEL0, file = paste0("../outputs/datasets/iotc_catch_all_1m_firms_level0_", Sys.Date(), ".csv"), row.names = FALSE)
```

```{r DataExportWithCodeLists}
# Read the Data dictionary table
DDD = data.table::data.table(openxlsx::read.xlsx("../inputs/GTA_DDD.xlsx", sheet = "DDD"))

# Create empty workbook
IOTC_CA_M_LEVEL0_WB = createWorkbook("IOTC_CA_M_LEVEL0")

# Add Fields definition
addWorksheet(IOTC_CA_M_LEVEL0_WB, "FIELDS")
writeDataTable(IOTC_CA_M_LEVEL0_WB, sheet = "FIELDS", x = DDD, rowNames = TRUE, tableStyle = "TableStyleLight11")
setColWidths(IOTC_CA_M_LEVEL0_WB, sheet = "FIELDS", cols = 1:nrow(DDD), widths = "auto")

# Add data set
addWorksheet(IOTC_CA_M_LEVEL0_WB, "DATA")
writeDataTable(IOTC_CA_M_LEVEL0_WB, sheet = "DATA", IOTC_CA_M_LEVEL0, startRow = 1, startCol = 1, tableStyle = "TableStyleMedium4")

# Add ASFIS species code list
addWorksheet(IOTC_CA_M_LEVEL0_WB, "SPECIES")
writeDataTable(IOTC_CA_M_LEVEL0_WB, sheet = "SPECIES", SPECIES_CODE_LIST, startRow = 1, startCol = 1, tableStyle = "TableStyleMedium4")

# Add ISSCFG gear code list
addWorksheet(IOTC_CA_M_LEVEL0_WB, "GEAR")
writeDataTable(IOTC_CA_M_LEVEL0_WB, sheet = "GEAR", GEAR_CODE_LIST, startRow = 1, startCol = 1, tableStyle = "TableStyleMedium4")

# Add FIRMS fleet code list
addWorksheet(IOTC_CA_M_LEVEL0_WB, "FLEET")
writeDataTable(IOTC_CA_M_LEVEL0_WB, sheet = "FLEET", FLEET_CODE_LIST, startRow = 1, startCol = 1, tableStyle = "TableStyleMedium4")

# Save the workbook
saveWorkbook(IOTC_CA_M_LEVEL0_WB, paste0("../outputs/datasets/iotc_catch_all_1m_firms_level0_", Sys.Date(), ".xlsx"), overwrite = TRUE)
```

```{r ExportZip}
OutputDir = paste0("../outputs/datasets/", Sys.Date())

if(!dir.exists(OutputDir)) {dir.create(OutputDir)}

zip::zip(zipfile = paste0(OutputDir, "/IOTC_FIRMS_GTA_EXPORT_LEVEL0_", Sys.Date(), ".zip"), files = list.files(path = "../outputs/datasets/", pattern = ".csv", full.names = TRUE), include_directories = FALSE, mode = "cherry-pick")
```

