```{r Species_Gear_Fleet_Mapping, echo = TRUE}
# Merge with ASFIS species list
CA_55M_MAPPED_SPECIES = merge(CA_55M, MAPPING_SPECIES[src_codingsystem == "species_iotc" & trg_codingsystem == "species_asfis", .(src_code, species = trg_code)], by.x = "SPECIES_CODE", by.y = "src_code", all.x = TRUE)

# Merge with ISSCFG gear list
CA_55M_MAPPED_SPECIES_GEAR = merge(CA_55M_MAPPED_SPECIES, MAPPING_GEAR[src_codingsystem == "gear_iotc" & trg_codingsystem == "isscfg_revision_1", .(src_code, gear = trg_code)], by.x = "GEAR_CODE", by.y = "src_code", all.x = TRUE)

# Merge with FIRMS fleet list
CA_55M_MAPPED_SPECIES_GEAR_FLEET = merge(CA_55M_MAPPED_SPECIES_GEAR, MAPPING_FLEET[src_codingsystem == "fleet_iotc" & trg_codingsystem == "fleet_firms", .(src_code, fleet = trg_code)], by.x = "FLEET_CODE", by.y = "src_code", all.x = TRUE)
```

```{r Mapping_Check, echo = FALSE}
# Check if missing species
if (nrow(CA_55M_MAPPED_SPECIES[is.na(species)])>0) print( paste("The following species codes are missing from the mapping: ", paste0(unique(CA_55M_MAPPED_SPECIES[is.na(species), SPECIES_CODE]), collapse = "|")))

# Check if missing gears
if (nrow(CA_55M_MAPPED_SPECIES_GEAR[is.na(gear)])>0) print( paste("The following gear codes are missing from the mapping: ", paste0(unique(CA_55M_MAPPED_SPECIES_GEAR[is.na(gear), GEAR_CODE]), collapse = "|")))

# Check if missing fleets
if (nrow(CA_55M_MAPPED_SPECIES_GEAR_FLEET[is.na(fleet)])>0) print( paste("The following flag codes are missing from the mapping: ", paste0(unique(CA_55M_MAPPED_SPECIES_GEAR_FLEET[is.na(fleet), FLAG_CODE]), collapse = "|")))
```

```{r Dataset_Code_lists, echo = FALSE}
# ASFIS code list
SPECIES_CODE_LIST = SPECIES[`3A_CODE` %in% unique(CA_55M_MAPPED_SPECIES_GEAR_FLEET$species), .(`3A_CODE`, Scientific_name, English_name, French_name, Family, Order)][order(`3A_CODE`)]

# Gear code list
GEAR_CODE_LIST = GEARS[code %in% unique(CA_55M_MAPPED_SPECIES_GEAR_FLEET$gear)][order(code)][order(code)]

# Fleet code list
FLEET_CODE_LIST = FLEETS[code %in% unique(CA_55M_MAPPED_SPECIES_GEAR_FLEET$fleet)][order(code)]
```